### ISSUE TITLE
Création d'un utilisateur

### ISSUE THREAD

**Issue by franckvalot** [AlinaBordei/web5A_BRIDOUX_PRISER_VALNET_VALOT#1]
Gérer la création d'un utilisateur et l'ajouter dans la base de donné. S'assurer que l'utilisateur soit bien unique, et que le mot de passe soit existant. Appliquer les contraintes nécessaires.

6h

**Comment by clarouu** [comment]
Côté ajax : proposition :

//exemple
uname = "Alina"; //en vrai c'est quelque chose du genre : uname = $("#idDeTonInput").val();
pwd = "cocotte";
email = "alina.lacocotte@gmail.com";

var dataString = {username:uname, password:pwd, mail:email};

function addNewUser(dataString){
	$.ajax({
	  type: "POST",
	  url: "localhost:8080/addUser/" + dataString,
	  data: dataString,
	  success: success,
	  dataType: dataType
	}).done(function(){
		alert("Tu es enregistré !");	
	});	
}

**Comment by clarouu** [comment]
Ajax fonctionnel
worked : 4h30
left : 2h30

**Comment by clarouu** [comment]
PROBLEME : Pour s'assurer que l'utilisateur est bien unique, j'utilise un try/catch mais le catch ne fonctionne pas... Help please ! 

try {
		    users = jdbcTemplate.query(
	                "SELECT * FROM user WHERE name like ?", new Object[] { name },
	                (rs, rowNum) -> new User(rs.getInt("id"), rs.getString("name"), rs.getString("password"), rs.getString("mail"))
	        );
		    return "true";
	    }catch(EmptyResultDataAccessException e) {
	    	return "false";
	    }

**Comment by clarouu** [comment]
Vérifier que le nom de l'utilisateur est bien unique : ok
Worked : 2h30
Left : 1h-2h 
Vérifications sur champs vides du formulaire à faire

**Comment by clarouu** [comment]
Vérifications sur champs vides du formulaire en jQuery OK
Worked : 20 min
