### ISSUE TITLE
Ajout destinataire : auto-complétion 

### ISSUE THREAD

**Issue by AlinaBordei** [AlinaBordei/web5A_BRIDOUX_PRISER_VALNET_VALOT#12]

**Comment by clarouu** [comment]
SQL request OK
Worked : 20 min

**Comment by clarouu** [comment]
Function OK
Thanks to all the team to take a look and help me to improve it
Worked : 1h30
To do : get the list of contacts from the input and send it to controller --> for knowing who send and who receive

**Comment by clarouu** [comment]
Function for getting list of adressees ok
Worked : 45min
To do : Pass this list to the controller
Left : 2h

**Comment by clarouu** [comment]
Insert and match idConversation with each idUser (adressees) OK
Worked : 40 min
